name: test

on: [push, pull_request]

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run the tests
        run: npm test -- --coverage
      - name: Publish Code Coverage Results
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/coverage-final.json
